#!/bin/bash

# Filter requests referred by Google

exit

if [[ "$#" != 1 ]]; then
    exit_with_error "No arguments passed to $0"
fi

function main() {
    local file="$1"
    local is_open="$(is_open ${file})"

    # skip if file is open
    if [[ "${is_open}" != 0 ]]; then
        local stage4_file="${STAGE4}/${0##*/}-${file##*/[0-9][0-9]}"
        
        local size="$(stat --printf='%s' ${stage4_file})"

        # Remove stage4_file if empty (20 byte gzip header)
        if [[ "${size}" == 20 ]]; then
            rm -- "${stage4_file}"
        fi
    fi
}

main "$@"
